config/routes.rb
Rails.application.routes.draw do

  
  resources :app_settings
  resources :entertainments


  resources :worlds do 
    resources :comments
  end

    resources :comments do
      member do
        put "like", to: "comments#like"
        put "unlike", to: "comments#unlike" 
    end
  end

  resources :tecs
  resources :googles
  devise_for :users
  root to: "pages#index"
  resource :subscription
  resources :subscriptions, only: [:new, :create, :destroy]


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/models/world.rb
class World < ApplicationRecord
  validates_uniqueness_of :title, case_sensitive: false
  # has_many :comments
  # paginates_per 2
  def self.search(term)
    if term
      where('title ILIKE ? OR source ILIKE ?', "%#{term}%", "%#{term}%").order('id DESC')
    else
      order('id DESC') 
    end
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :set_world, only: [:show, :edit, :update, :destroy]

  # GET /world
  # GET /world.json
  def index
    @worlds = World.search(params[:term]).order(created_at: :desc)
    if @worlds.class == Array
    # @world = Kaminari.paginate_array(@world).page(params[:page])
    @worlds = World.order(created_at: :desc).page params[:page]

    else
    # @world = World.order(created_at: :desc).page params[:page]
    @worlds = Kaminari.paginate_array(@worlds).page(params[:page]).per(12) 
    end


    Pusher.trigger('my-channel', 'my-event', {
      message: 'hello world'
    })
  end

  # GET /world/1
  # GET /world/1.json
  def show
    # is_admin?
    @comment = Comment.new 
  end

  # GET /world/new
  def new
    is_admin?
    @world = World.new
  end

  # GET /world/1/edit
  def edit
    is_admin?
  end

  # POST /world
  # POST /world.json
  def create
    @world = World.new(world_params)

    respond_to do |format|
      if @world.save
        format.html { redirect_to @world, notice: 'World was successfully created.' }
        format.json { render :show, status: :created, location: @world }
      else
        format.html { render :new }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /world/1
  # PATCH/PUT /world/1.json
  def update
    is_admin?
    respond_to do |format|
      if @world.update(world_params)
        format.html { redirect_to @world, notice: 'World was successfully updated.' }
        format.json { render :show, status: :ok, location: @world }
      else
        format.html { render :edit }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /world/1
  # DELETE /world/1.json
  def destroy
    is_admin?
    @world.destroy
    respond_to do |format|
      format.html { redirect_to world_index_url, notice: 'World was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_world
      @world = World.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def world_params
      params.require(:world).permit(
      :title, 
      :source, 
      :title_url, 
      :image_url
      )
    end
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/worlds/_form.html.erb
<%= simple_form_for(@world) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :source %>
    <%= f.input :title_url %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/worlds/_jq.html.erb
<script>
  
  // Enable pusher logging - don't include this in production
  Pusher.logToConsole = true;
  var pusher = new Pusher('3b8fe903171ecd2c3a5e', {
    cluster: 'us2',
    encrypted: true
  });
  var channel = pusher.subscribe('my-channel');
  channel.bind('my-event', function(data) {
    //$("#the-message").append( '<p>' + data.user_email + ': ' +  data.comment + '</p>'); 

    $("#the-message").append( 
      
'<div class="card border-primary mb-3">' +
'<div class="card-header">' + data.user_email + '</div>' + 
'<div class="card-body">' + '<h4 class="card-title">' + '</h4>' +
'<p class="card-text">' + data.comment + '</p>' + '</div>' + '</div>' +

);


    $('#comment_comment').val('');   
  });
</script>

app/views/worlds/edit.html.erb
<h1>Editing World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Show', @world %> |
<%= link_to 'Back', worlds_path %>

app/views/worlds/index.html.erb
<%= paginate @worlds %>
<br><br>
<%= form_tag(worlds_path, method: :get, :class => 'form-inline') do %>
<div class="toolbar">
  <div class="actions">
    <i class="actions__item zmdi zmdi-search" data-sa-action="toolbar-search-open"></i>
  </div>
  <%= text_field_tag :term, params[:term], class: 'form-control' %>
  <%= submit_tag 'Search', class: 'btn btn-danger' %>
  <%= link_to "Clear Search", worlds_path, class: 'btn btn-info' %>
  <div class="toolbar__search" style="display: none;">
    <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-sa-action="toolbar-search-close"></i>
  </div>
</div>
<% end %>
<br><br>
<div class='row'>
  <% @worlds.each do |world| %>
  <div class='col-sm-3'>
    <div class="card mb-3">
      
      <h3 class="card-header"><%= truncate(world.title, length: 60) %></h3> 
      <div class="card-body">
        <h5 class="card-title"><%= (world.source) %></h5>
        <%= link_to 'Show Story', world_path(world) %>
      </div>
      <%= link_to world.title_url, target: :_blank do %>
      <% end %>
      <%= image_tag (world.image_url if !world.image_url.nil? ) %>
      <div class="card-footer text-muted">
        Story Published <%= time_ago_in_words(world.created_at) %> ago
      </div>
    </div>
  </div>
  <% end %>
</div>
<br>

<%= link_to 'Sample Adminstration Link', new_world_path, class: 'btn btn-outline-primary' %>

app/views/worlds/new.html.erb
<h1>New World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Back', worlds_path %>

app/views/worlds/show.html.erb
<div class="jumbotron">
  <%= link_to @world.title_url, target: :_blank do %>
  <h1 class="display-4"><%= truncate(@world.title, length: 120) %></h1>
  <p class="lead"><%= (@world.source) %></p>
  <hr class="my-4">
  <p>      
    <%= image_tag (@world.image_url if !@world.image_url.nil? ) %>
  <div class="card-footer text-muted">
    <% end %>
    Story Published <%= time_ago_in_words(@world.created_at) %> ago
  </div>
  </p>
  <p class="lead">
  </p>
</div>
<%= render 'comments/form' %>
<p id='the-message'></p>
<% @world.comments.each do |comment| %> 
<div class="card border-primary mb-3">
  <div class="card-header"><%= comment.user.email %>
  </div>
  <div class="card-body">
    <h4 class="card-title"></h4>
    <p class="card-text"><%= comment.comment %></p>
  </div>
</div>
<%= link_to like_comment_path(comment), class: 'like-btn',  remote: true, method: :put do %>
<span class='green'>
  <p id='dynamic-heart-<%= comment.id %>' class='heart'>
    <i class='fa fa-arrow-up fa-1x'></i> 
    <span class='dynamic-likes<%= comment.id %>'> <%= comment.get_likes.size %></span>
  </p>
</span>
<% end %>
<%= link_to unlike_comment_path(comment), class: 'like-btn',  remote: true, method: :put do %>
<span class='red'>
  <p id='dynamic-heart-<%= comment.id %>' class='heart'>
    <i class='fa fa-arrow-down fa-1x'></i> 
    <span class='dynamic-dislikes<%= comment.id %>'> <%= comment.get_dislikes.size %></span>
  </p>
</span>
<% end %>
<% end %>
<%= render @world.comments %> 
<%= render 'jq' %>  
</div>
</div>
</div>