config/routes.rb
Rails.application.routes.draw do

  
  resources :app_settings
  resources :entertainments


  resources :worlds do 
    resources :comments
  end

    resources :comments do
      member do
        put "like", to: "comments#like"
        put "unlike", to: "comments#unlike" 
    end
  end

  resources :tecs
  resources :googles
  devise_for :users
  root to: "pages#index"
  resource :subscription
  resources :subscriptions, only: [:new, :create, :destroy]


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/models/google.rb
class Google < ApplicationRecord
  validates :title, uniqueness: true
  # paginates_per 2
  def self.search(term)
    if term
      where('title ILIKE ? OR source ILIKE ?', "%#{term}%", "%#{term}%").order('id DESC')
    else
      order('id DESC') 
    end
  end
end

app/controllers/googles_controller.rb
class GooglesController < ApplicationController
  before_action :set_google, only: [:show, :edit, :update, :destroy]

  # GET /google
  # GET /google.json
  def index
    @googles = Google.search(params[:term]).order(created_at: :desc)
    if @googles.class == Array
    # @google = Kaminari.paginate_array(@google).page(params[:page])
    @googles = Google.order(created_at: :desc).page params[:page]

    else
    # @google = Google.order(created_at: :desc).page params[:page]
    @googles = Kaminari.paginate_array(@googles).page(params[:page]).per(12) 
    end
  end

  # GET /google/1
  # GET /google/1.json
  def show
    is_admin?
  end

  # GET /google/new
  def new
    is_admin?
    @google = Google.new
  end

  # GET /google/1/edit
  def edit
    is_admin?
  end

  # POST /google
  # POST /google.json
  def create
    @google = Google.new(google_params)

    respond_to do |format|
      if @google.save
        format.html { redirect_to @google, notice: 'Google was successfully created.' }
        format.json { render :show, status: :created, location: @google }
      else
        format.html { render :new }
        format.json { render json: @google.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /google/1
  # PATCH/PUT /google/1.json
  def update
    is_admin?
    respond_to do |format|
      if @google.update(google_params)
        format.html { redirect_to @google, notice: 'Google was successfully updated.' }
        format.json { render :show, status: :ok, location: @google }
      else
        format.html { render :edit }
        format.json { render json: @google.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /google/1
  # DELETE /google/1.json
  def destroy
    is_admin?
    @google.destroy
    respond_to do |format|
      format.html { redirect_to google_index_url, notice: 'Google was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_google
      @google = Google.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def google_params
      params.require(:google).permit(
      :title, 
      :source, 
      :title_url, 
      :image_url
      )
    end
end

app/helpers/googles_helper.rb
module GooglesHelper
end

app/views/googles/_form.html.erb
<%= simple_form_for(@google) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :source %>
    <%= f.input :title_url %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/googles/edit.html.erb
<h1>Editing Google</h1>

<%= render 'form', google: @google %>

<%= link_to 'Show', @google %> |
<%= link_to 'Back', googles_path %>

app/views/googles/index.html.erb
<%= paginate @googles %>
<br><br>
<%= form_tag(googles_path, method: :get, :class => 'form-inline') do %>
<div class="toolbar">
  <div class="actions">
    <i class="actions__item zmdi zmdi-search" data-sa-action="toolbar-search-open"></i>
  </div>
  <%= text_field_tag :term, params[:term], class: 'form-control' %>
  <%= submit_tag 'Search', class: 'btn btn-danger' %>
  <%= link_to "Clear Search", googles_path, class: 'btn btn-info' %>
  <div class="toolbar__search" style="display: none;">
    <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-sa-action="toolbar-search-close"></i>
  </div>
</div>
<% end %>
<div class='row'>
  <% @googles.each do |google| %>
  <div class='col-sm-3'>
    <div class="card mb-3">
      <%= link_to google.title_url, target: :_blank do %>
      <h3 class="card-header"><%= truncate(google.title, length: 60) %></h3>
      <div class="card-body">
        <h5 class="card-title"><%= (google.source) %></h5>
        <h6 class="card-subtitle text-muted"><%= truncate(google.body) %></h6>
      </div>
      <% end %>
      <%= image_tag (google.image_url) %>
      <div class="card-footer text-muted">
        Story Published <%= time_ago_in_words(google.created_at) %> ago
      </div>
    </div>
  </div>
  <% end %>
</div>
<br>

<%= link_to 'New Google', new_google_path %>

app/views/googles/new.html.erb
<h1>New Google</h1>

<%= render 'form', google: @google %>

<%= link_to 'Back', googles_path %>

app/views/googles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @google.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @google.body %>
</p>

<p>
  <strong>Source:</strong>
  <%= @google.source %>
</p>

<p>
  <strong>Title url:</strong>
  <%= @google.title_url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @google.image_url %>
</p>

<%= link_to 'Edit', edit_google_path(@google) %> |
<%= link_to 'Back', googles_path %>