config/routes.rb
Rails.application.routes.draw do

  
  resources :app_settings
  resources :entertainments


  resources :worlds do 
    resources :comments
  end

    resources :comments do
      member do
        put "like", to: "comments#like"
        put "unlike", to: "comments#unlike" 
    end
  end

  resources :tecs
  resources :googles
  devise_for :users
  root to: "pages#index"
  resource :subscription
  resources :subscriptions, only: [:new, :create, :destroy]


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/views/layouts/_footer.html.erb
<br><br>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">
        &copy; <%= Time.now.strftime('%Y')%> <%= @app_setting.app_name %> |
        <%= @app_setting.city %> <%= @app_setting.state %>
        <span class='float-right'>
          <strong>
            News You Can Trust
          </strong>
        </span>
        </span>
      </div>
    </footer>
    <br><br>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_path do %>
    <div class='navbar-brand'>
      <%= @app_setting.app_name %>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav w-100">
      <li class="nav-item">
        <%= link_to "World News", worlds_path, class: 'nav-link' %>
      </li>
      <% if current_user && current_user.subscribed? %>
      <li class="nav-item">
        <%= link_to "Technology", tecs_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Entertainment", entertainments_path, class: 'nav-link' %>
      </li>
      <% end %>

      <% if current_user.try(:admin?) %>
        <li class="nav-item">
          <%= link_to "Redis | Sidekiq", sidekiq_web_path, class: 'nav-link', target: '_blank' %>
        </li>
        <li class="nav-item">
          <%= link_to "Administration", rails_admin_path, class: 'nav-link', target: '_blank' %>
        </li>
      <% end %>

      <% if !current_user %>
      <li class="nav-item dropdown ml-auto">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Sign In", new_user_session_path, class: 'dropdown-item' %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'dropdown-item' %>

        </div>
      </li>
      <% else %>
            <li class="nav-item dropdown ml-auto">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <%= current_user.email %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          
          <%= link_to "My Account", edit_user_registration_path, class: 'dropdown-item' %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
      <% end %>
    </ul>  
  </div>
</nav>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @app_setting.tab_name %></title>
    <%= csrf_meta_tags %>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'theme.css', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
    <%= tag :meta, name: 'stripe-public-key', content: Rails.application.credentials.stripe_public_key %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    
  <div class='container'>
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
      <%= render 'layouts/footer' %>
  </body>
</html>